/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2205 from the
 * contents of MCrypto.xs. Do not edit this file, edit MCrypto.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "MCrypto.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "MCrypto.h"

#include "MCryptoDef.c"

void
DumpMemory(const char *label, char *v, int len) {
    const char *hex[] = {"0", "1", "2", "3", "4", "5", "6", "7", 
                         "8", "9", "A", "B", "C", "D", "E", "F"};
    int i = 0;
    printf("_xs %s(%d): ", label, len);
    for (i = 0; i < len; ++i) {
        printf("%s%s", hex[(v[i] & 0xF0) >> 4], hex[v[i] & 0x0F]);
    }
    printf("\n");
}

#line 33 "MCrypto.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 85 "MCrypto.c"

XS(XS_MCrypto_packet_decrypt); /* prototype to pass -Wmissing-prototypes */
XS(XS_MCrypto_packet_decrypt)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "sv, decrypt_key, decrypt_IV, index");
    {
	SV *	sv = ST(0);
	SV *	decrypt_key = ST(1);
	SV *	decrypt_IV = ST(2);
	SV *	index = ST(3);
	SV *	RETVAL;
#line 32 "MCrypto.xs"
    char *out = malloc(SvCUR(sv));
    if (!out) {
        RETVAL = &PL_sv_undef;
        goto done;
    }

    char *buf = (char *)SvPV(sv, SvCUR(sv));
    struct crypto_struct *mas = get_ciphertab();
    struct crypto_struct *crypto = &mas[SvIV(index)];

    //printf("_xs name: %s\n", crypto->name);

    //DumpMemory("input_sv", SvPV(sv, SvCUR(sv)), SvCUR(sv));
    //DumpMemory("decrypt_key", SvPV(decrypt_key, SvCUR(decrypt_key)), SvCUR(decrypt_key));
    //DumpMemory("decrypt_IV", SvPV(SvRV(decrypt_IV), SvCUR(SvRV(decrypt_IV))), SvCUR(SvRV(decrypt_IV)));

    if (crypto->set_decrypt_key(crypto, (char *)SvPV(decrypt_key, SvCUR(decrypt_key))) < 0) {
        free(out);
        RETVAL = &PL_sv_undef;
        goto done;
    }

    //DumpMemory("_xs decrypt inside", crypto->key, crypto->keysize/8);

    int iv_length = SvCUR(SvRV(decrypt_IV));
    char *dec_iv = malloc(iv_length);
    if (!dec_iv) {
        free(out);
        RETVAL = &PL_sv_undef;
        goto done;
    }

    //printf("iv_length: %d\n", iv_length);

    memcpy(dec_iv, SvPV(SvRV(decrypt_IV), iv_length), iv_length);
    //DumpMemory("_xs decrypt inside", crypto->key, crypto->keysize / 8);
    crypto->xdecrypt(crypto, buf, out, SvCUR(sv), dec_iv);
    //DumpMemory("_xs decrypt inside", crypto->key, crypto->keysize / 8);
    sv_setpvn(SvRV(decrypt_IV), dec_iv, iv_length);

    RETVAL = newSVpv(out, SvCUR(sv));

    free(dec_iv);
    free(out);

    done:

#line 151 "MCrypto.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_MCrypto_packet_encrypt); /* prototype to pass -Wmissing-prototypes */
XS(XS_MCrypto_packet_encrypt)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "sv, encrypt_key, encrypt_IV, index");
    {
	SV *	sv = ST(0);
	SV *	encrypt_key = ST(1);
	SV *	encrypt_IV = ST(2);
	SV *	index = ST(3);
	SV *	RETVAL;
#line 90 "MCrypto.xs"
    char *out = malloc(SvCUR(sv)); 
    if (!out) {
        RETVAL = &PL_sv_undef;
        goto done;
    }

    char *buf = (char *)SvPV(sv, SvCUR(sv));
    struct crypto_struct *mas = get_ciphertab();
    struct crypto_struct *crypto = &mas[SvIV(index)];

    if (crypto->set_encrypt_key(crypto, SvPV(encrypt_key, SvCUR(encrypt_key))) < 0) {
        free(out);
        RETVAL = &PL_sv_undef;
        goto done;
    }

    int iv_length = SvCUR(SvRV(encrypt_IV));
    char *enc_iv = malloc(iv_length);
    if (!enc_iv) {
        free(out);
        RETVAL = &PL_sv_undef;
        goto done;
    }

    memcpy(enc_iv, SvPV(SvRV(encrypt_IV), iv_length), iv_length);
    crypto->xencrypt(crypto, buf, out, SvCUR(sv), enc_iv);
    sv_setpvn(SvRV(encrypt_IV), enc_iv, iv_length);

    RETVAL = newSVpv(out, SvCUR(sv));

    free(enc_iv);
    free(out);

    done:

#line 211 "MCrypto.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_MCrypto_compute_hmac); /* prototype to pass -Wmissing-prototypes */
XS(XS_MCrypto_compute_hmac)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "sv, encryptMAC");
    {
	SV *	sv = ST(0);
	SV *	encryptMAC = ST(1);
	SV *	RETVAL;
#line 133 "MCrypto.xs"
    char *out = malloc(EVP_MAX_MD_SIZE);
    if (!out) {
        RETVAL = &PL_sv_undef;
        goto done;
    }

    HMAC_CTX *ctx = hmac_init(SvPV(encryptMAC, SvCUR(encryptMAC)), 20, HMAC_SHA1);
    if (ctx == NULL) {
        free(out);
        RETVAL = &PL_sv_undef;
        goto done;
    }

    int finallen;
    hmac_update(ctx, (char *)SvPV(sv, SvCUR(sv)), (int)SvCUR(sv));
    hmac_final(ctx, out, &finallen);

    RETVAL = newSVpv(out, finallen);

    free(out);

    done:

#line 257 "MCrypto.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_MCrypto_packet_hmac_verify); /* prototype to pass -Wmissing-prototypes */
XS(XS_MCrypto_packet_hmac_verify)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "sv, decryptMAC, mac");
    {
	SV *	sv = ST(0);
	SV *	decryptMAC = ST(1);
	SV *	mac = ST(2);
	IV	RETVAL;
	dXSTARG;
#line 165 "MCrypto.xs"
    unsigned char hmacbuf[EVP_MAX_MD_SIZE] = {0};

    char *out = malloc(EVP_MAX_MD_SIZE);
    if (!out) {
        RETVAL = 0;
        goto done;
    }

    HMAC_CTX *ctx = hmac_init(SvPV(decryptMAC, SvCUR(decryptMAC)), 20, HMAC_SHA1);
    if (ctx == NULL) {
        free(out);
        RETVAL = 0;
        goto done;
    }

    int finallen;
    hmac_update(ctx, (char *)SvPV(sv, SvCUR(sv)), (int)SvCUR(sv));
    hmac_final(ctx, hmacbuf, &finallen);

    if (!memcmp((char *)SvPV(mac, SvCUR(mac)), hmacbuf, finallen)) {
        RETVAL = 1;
    } else {
        RETVAL = 0;
    }

    free(out);

    done:

#line 311 "MCrypto.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_MCrypto_list_cryptors); /* prototype to pass -Wmissing-prototypes */
XS(XS_MCrypto_list_cryptors)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	AV *	RETVAL;
#line 200 "MCrypto.xs"
    AV *av = newAV();

    struct crypto_struct *cipher_tab = get_ciphertab();
    for (int i = 0; cipher_tab[i].name; ++i) {
        struct crypto_struct *ct = &cipher_tab[i];
        av_push(av, newSVpv(ct->name, strlen(ct->name)));
        av_push(av, newSViv(ct->blocksize));
        av_push(av, newSViv(ct->keylen));
        av_push(av, newSViv(ct->keysize));
    }

    RETVAL = av;
    sv_2mortal((SV *)RETVAL);

#line 345 "MCrypto.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_MCrypto); /* prototype to pass -Wmissing-prototypes */
XS(boot_MCrypto)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("MCrypto::packet_decrypt", XS_MCrypto_packet_decrypt, file);
        newXS("MCrypto::packet_encrypt", XS_MCrypto_packet_encrypt, file);
        newXS("MCrypto::compute_hmac", XS_MCrypto_compute_hmac, file);
        newXS("MCrypto::packet_hmac_verify", XS_MCrypto_packet_hmac_verify, file);
        newXS("MCrypto::list_cryptors", XS_MCrypto_list_cryptors, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

